AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example demonstrating AWS Lambda function
Resources:
  helloWorldPython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: s3://himanjan-code-sam/be5d01111cc169a11b5e20b44093bb04
      Description: A starter lambda function
      MemorySize: 128
      Timeout: 3
      Events:
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
